services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    image: redis
    command: redis-server --requirepass PASSWORD --appendonly yes
    hostname: redis
    ports:
      - 6379:6379
